name: pytest

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Build
              run: |
                  cargo build
